import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProviders from "./utils/ClientProviders";
import Navbar from "./comps/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-screen h-screen flex bg-black text-white border-white font-semibold antialiased`}
      >
        <ClientProviders>
          {/* Sidebar */}
          <div className="flex-none">
            <Navbar />
          </div>

          <div className="flex-1 overflow-y-auto">{children}</div>
        </ClientProviders>
      </body>
    </html>
  );
}
