import type { Metadata } from "next";
import { Encode_Sans } from "next/font/google";
import "./globals.css";
import ClientProviders from "./utils/ClientProviders";
import Navbar from "./comps/Navbar";
import { Boxes } from "lucide-react";
import Head from "next/head";

const font = Encode_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Commerce Shop",
  description: "Generated by create next app",
  icons: {
    icon: "../public/boxes.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="./assets/boxes.svg" type="image/svg+xml" />
      </Head>
      <body
        className={`${font.className} w-screen h-screen flex bg-black text-white border-white font-semibold antialiased`}
      >
        <ClientProviders>
          <div className="flex-none">
            <Navbar />
          </div>

          <div className="flex-1 overflow-y-auto">{children}</div>
        </ClientProviders>
      </body>
    </html>
  );
}
